### ISSUE TITLE
Run DeepWeb tests

### ISSUE THREAD

**Issue by Chobbes** [Quick700/Quick700#11]
@liyishuai Currently getting this problem when I run make in the Deepweb directory:

```
make[1]: Entering directory '/home/calvin/git/DeepWeb/src'
make -C Custom build
make[2]: Entering directory '/home/calvin/git/DeepWeb/src/Custom'
make -f Makefile.coq
make[3]: Entering directory '/home/calvin/git/DeepWeb/src/Custom'
make[4]: Nothing to be done for 'real-all'.
make[3]: Leaving directory '/home/calvin/git/DeepWeb/src/Custom'
make[2]: Leaving directory '/home/calvin/git/DeepWeb/src/Custom'
make -C Free coq
make[2]: Entering directory '/home/calvin/git/DeepWeb/src/Free'
make -f Makefile.coq
make[3]: Entering directory '/home/calvin/git/DeepWeb/src/Free'
make[4]: Nothing to be done for 'real-all'.
make[3]: Leaving directory '/home/calvin/git/DeepWeb/src/Free'
make[2]: Leaving directory '/home/calvin/git/DeepWeb/src/Free'
make -C DeepWeb coq
make[2]: Entering directory '/home/calvin/git/DeepWeb/src/DeepWeb'
make[3]: Entering directory '/home/calvin/git/DeepWeb/src/ocamllib'
ocamlbuild ExtractionClient.cmxs
+ /usr/bin/ocamlc.opt -c -o ExtractionClient.cmo ExtractionClient.ml
File "ExtractionClient.ml", line 17, characters 8-18:
Error: Unbound value getenv_opt
Command exited with code 2.
Compilation unsuccessful after building 2 targets (1 cached) in 00:00:00.
make[3]: *** [Makefile:6: ExtractionClient.cmxs] Error 10
make[3]: Leaving directory '/home/calvin/git/DeepWeb/src/ocamllib'
make[2]: *** [Makefile:61: extraction] Error 2
make[2]: Leaving directory '/home/calvin/git/DeepWeb/src/DeepWeb'
make[1]: *** [Makefile:12: deepweb] Error 2
make[1]: Leaving directory '/home/calvin/git/DeepWeb/src'
make: *** [Makefile:31: all] Error 2
```

Any idea?

**Comment by liyishuai** [comment]
I should really get rid of OCaml plugins. Fixing.

**Comment by Chobbes** [comment]
@liyishuai any luck?

**Comment by liyishuai** [comment]
Under process. Except to run this afternoon.

**Comment by liyishuai** [comment]
Almost done. You could try integrating AFL with [c-mutation](/QuickChick/QuickChick/tree/FuzzChick/examples/c-mutation), [pyml](/QuickChick/QuickChick/tree/FuzzChick/examples/pyml), or [python-io](/QuickChick/QuickChick/tree/FuzzChick/examples/python-io) examples before I finish.

**Comment by Chobbes** [comment]
What do you mean by that @liyishuai? Isn't the FuzzChick stuff pretty automatic? What kind of thing do I need to look at for integration?

This is a good idea, I just need a bit more of an overview.

**Comment by liyishuai** [comment]
It should be straightforward. You might need to checkout `Driver.v` under `fuzz-ifc`.

**Comment by Chobbes** [comment]
Hmmm. I'm not sure I really understand what `Driver.v` is / what it does.

What do these things mean?

- SSNI
- MSNI
- EENI

**Comment by liyishuai** [comment]
They represent:
- single-step noninterference
- multi-step noninterference
- end-to-end noninterference

See [Catalin's paper](//dl.acm.org/citation.cfm?id=2544174.2500574).

**Comment by Chobbes** [comment]
Mmmm, still having problems.

```
$ make testapache
test_server
Using default tag: latest
latest: Pulling from ysli/apache
Digest: sha256:3f9bee72ca29ef35a3b5f63460507655a8efa66f3688558cf647496995c870ab
Status: Image is up to date for ysli/apache:latest
3b3d037e98a718aeaa6b9be6ff20cfeee8b184fb885f7659b9c5d47f916ab5ea
make testexternal SERVER=apache
make[1]: Entering directory '/home/calvin/git/DeepWeb/src/DeepWeb'
quickChick -color -top DeepWeb -ocamlbuild '-libs unix,str -I Util' -cmd 'make coq'  -s ExternalServerTests
Testing base...
make[2]: Entering directory '/home/calvin/git/DeepWeb/src/_qc_DeepWeb.tmp'
make[3]: Entering directory '/home/calvin/git/DeepWeb/src/_qc_DeepWeb.tmp'
COQDEP VFILES
COQC QuickChickTop.v
make[3]: Leaving directory '/home/calvin/git/DeepWeb/src/_qc_DeepWeb.tmp'
make[2]: Leaving directory '/home/calvin/git/DeepWeb/src/_qc_DeepWeb.tmp'
/usr/bin/ocamlc.opt -c -I Util -o RandomQC.cmi RandomQC.mli
+ /usr/bin/ocamlc.opt -c -I Util -o RandomQC.cmi RandomQC.mli
File "RandomQC.mli", line 5, characters 22-46:
Error: Unbound module QuickChickLib
Command exited with code 2.
Hint: Recursive traversal of subdirectories was not enabled for this build,
  as the working directory does not look like an ocamlbuild project (no
  '_tags' or 'myocamlbuild.ml' file). If you have modules in subdirectories,
  you should add the option "-r" or create an empty '_tags' file.
  
  To enable recursive traversal for some subdirectories only, you can use the
  following '_tags' file:
  
      true: -traverse
      <dir1> or <dir2>: traverse
      
Exited with status 10
Fatal error: exception Failure("Ocamlbuild failure")
make[1]: *** [Makefile:140: testexternal] Error 2
make[1]: Leaving directory '/home/calvin/git/DeepWeb/src/DeepWeb'
make: *** [Makefile:143: testapache] Error 2
```

**Comment by Chobbes** [comment]
I'm also not really sure what we need from Driver.v if it's all specific to the IFC example?

**Comment by liyishuai** [comment]
DeepWeb only works with `8.8` branch, not `FuzzChick`.

**Comment by Chobbes** [comment]
Ah, okay. Gotcha. Do we know what we need to change for it to work on FuzzChick?

My understanding of FuzzChick was that it basically just replaced the RNG with essentially a fuzzer bitstream. Why would anything that's using to test with QuickChick care about that?

**Comment by liyishuai** [comment]
We just need to have it running. You could start a new branch in DeepWeb that works with FuzzChick.
I’m going offline and will return after 21:30.

**Comment by Chobbes** [comment]
@liyishuai I don't think that answers the question.

I'm not sure I understand why we would need to change anything in the DeepWeb tests in order to use FuzzChick.

- What kind of things do we need to change in order to make QuickChick tests work with FuzzChick?
  + I thought FuzzChick just changed the random number generation used to generate data types more or less?
- What is the *it* that we "just need to have" running? Are you just saying that we need to "have DeepWeb tests running with FuzzChick?"

I need more information about FuzzChick in order to make progress with it.

**Comment by liyishuai** [comment]
I meant tweaking DeepWeb so that FuzzChick can drive its tests. Currently DeepWeb + FuzzChick = compilation error, right?
